[profile.release]
opt-level = "z"          # Optimization level (0-3, s, z)
lto = "fat"
codegen-units = 1      # Better optimization, slower compile
panic = "abort"        # Smaller binary, no unwinding
strip = true            # Strip debug symbols

[workspace]

resolver = "3"
members = [
    "crates/marina-apps", "crates/marina-core", "crates/marina-library",
    "crates/marina-romm",
    "crates/marina-store",
    "crates/marina-scanner",
    "crates/marina-store-sqlite",
    "crates/marina-test",
    "crates/marina-input",
    "crates/marina-runtime",
    "crates/marina-portmaster",
    "crates/marina-power",
    "crates/marina-logging",
    "crates/marina-config-derive",
    "crates/marina-ui-slint",
]

[workspace.package]
readme = "README.md"
rust-version = "1.95"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
base64 = "0.23"
bytesize = "2.7.0"
chrono = { version = "0.4", default-features = false, features = ["serde", "clock"] }
dotenvy = "0.15"
figment = { version = "0.10", features = ["toml"] }
dirs = "6"
futures-util = "0.3"
gilrs = "0.11.2"
i-slint-core = "=1.17.1"
reqwest = { version = "0.13", default-features = false, features = ["json", "query", "rustls"] }
resvg = "0.47"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = { version = "0.8", features = ["parse"] }
toml_edit = "0.19"
serde_urlencoded = "0.7"
rusqlite = "0.32"
thiserror = "2"
tokio = { version = "1", features = ["fs", "macros", "process", "rt-multi-thread", "sync", "time"] }
zip = { version = "8.6", default-features = false, features = ["deflate"] }
md-5 = "0.10"
nix = { version = "0.30", features = ["fs", "mount", "process", "sched", "user"] }
infer = { version = "0.19", default-features = false }
urlencoding = "2"
async-trait = "0.1"
tracing = "0.1"
url = "2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-journald = "0.3"
uuid = { version = "1", features = ["v4", "v5"] }
ulid = "1"
zbus = "5"
zbus_systemd = { version = "0.26100.0", features = ["hostname1", "locale1", "login1", "resolve1", "systemd1", "sysupdate1", "timedate1", "timesync1", "zbus-async-tokio"] }
nmrs = "3.5.3"

# marina
marina-apps = { path = "crates/marina-apps" }
marina-config-derive = { path = "crates/marina-config-derive" }
marina-core = { path = "crates/marina-core" }
marina-romm = { path = "crates/marina-romm" }
marina-store = { path = "crates/marina-store" }
marina-scanner = { path = "crates/marina-scanner" }
marina-library = { path = "crates/marina-library" }
marina-logging = { path = "crates/marina-logging" }
marina-store-sqlite = { path = "crates/marina-store-sqlite" }
marina-input = { path = "crates/marina-input" }
marina-runtime = { path = "crates/marina-runtime" }
marina-portmaster = { path = "crates/marina-portmaster" }
marina-power = { path = "crates/marina-power" }
