[package]
name = "marina-ui-slint"
version.workspace = true
edition.workspace = true
license.workspace = true

[build-dependencies]
slint-build = "1.12.1"

[dependencies]
slint = "1.12.1"
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp", "bmp"] }

dotenvy.workspace = true
marina-core.workspace = true
marina-library.workspace = true
marina-store-surrealdb.workspace = true
reqwest.workspace = true
tokio = { workspace = true, features = ["fs"] }
tracing.workspace = true
tracing-subscriber.workspace = true
