[package]
name = "marina-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
marina-config-derive.workspace = true
marina-core.workspace = true
marina-systemd.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
ulid.workspace = true
