[package]
name = "marina-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
marina-core.workspace = true
marina-library.workspace = true
async-trait.workspace = true
rusqlite = { workspace = true, features = ["bundled"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
