[Distribution]
Distribution=fedora
Architecture=arm64

[Output]
Format=sysext
Output=marina
OutputDirectory=../../target/marina-sysext
CompressOutput=no

[Content]
ExtraTrees=../../target/marina-sysext-root
CleanPackageMetadata=no
