import { GameCardData } from "card.slint";
import { Shelf } from "shelf.slint";

export component MainWindow inherits Window {
    in property <[GameCardData]> games;
    in property <length> shelf-height;

    width: 1280px;
    full-screen: false;
    height: 720px;
    title: "Marina";
    background: #1f2430;

    VerticalLayout {
        accessible-role: AccessibleRole.image;
        padding: 24px;

        Shelf {
            title: @tr("Library");
            games: root.games;
            content-height: root.shelf-height;
        }
        Image {
            // placeholder image...
            source: @image-url("adoo.jpg");
        }
        
    }
}
