import { Tokens } from "slintcn/theme/tokens.slint";
import { GameCardData } from "card.slint";
import { Shelf } from "shelf.slint";

export component MainWindow inherits Window {
    in property <[GameCardData]> games;
    in property <length> shelf-height;

    width: 1280px;
    height: 720px;
    title: "Marina";
    background: Tokens.color-background;

    VerticalLayout {
        padding: Tokens.spacing-2xl;
        spacing: Tokens.spacing-2xl;

        Shelf {
            title: "Library";
            games: root.games;
            content-height: root.shelf-height;
        }
    }
}
