[env]
CC = { value = "/usr/bin/clang", force = false }
CXX = { value = "/usr/bin/clang++", force = false }
# Use Mold instead of LLD for Rust's linker-plugin LTO path.
RUSTFLAGS = { value = "-Clinker-plugin-lto -Clinker=clang -Clink-arg=-fuse-ld=lld", force = false }
